---
Metadata:
Description: Template for an IBM Cloud Pak for Data deployment.

Parameters:
  ClusterName:
    Default: "immersionday-cluster"
    Description: Custom cluster name for kubernetes.io/cluster/tags.
    Type: String
    AllowedPattern: ^[0-9a-z-]*$

Resources:
  IAMRole00(Cluster_Name)openshiftclustercsidriversebscloudcredentials:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-cluster-csi-drivers-ebs-cloud-credentials"
      Description: "OpenShift role for openshift-cluster-csi-drivers/ebs-cloud-credentials"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "ec2:AttachVolume"
            - "ec2:CreateSnapshot"
            - "ec2:CreateTags"
            - "ec2:CreateVolume"
            - "ec2:DeleteSnapshot"
            - "ec2:DeleteTags"
            - "ec2:DeleteVolume"
            - "ec2:DescribeInstances"
            - "ec2:DescribeSnapshots"
            - "ec2:DescribeTags"
            - "ec2:DescribeVolumes"
            - "ec2:DescribeVolumesModifications"
            - "ec2:DetachVolume"
            - "ec2:ModifyVolume"
            Effect: "Allow"
          - Resource: "*"
            Action:
            - "kms:Decrypt"
            - "kms:Encrypt"
            - "kms:GenerateDataKey"
            - "kms:GenerateDataKeyWithoutPlainText"
            - "kms:DescribeKey"
            Effect: "Allow"
          - Condition:
              Bool:
                kms:GrantIsForAWSResource: true
            Resource: "*"
            Action:
            - "kms:RevokeGrant"
            - "kms:CreateGrant"
            - "kms:ListGrants"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-cluster-csi-drivers-ebs-cloud-crede"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub:
              - "system:serviceaccount:openshift-cluster-csi-drivers:aws-ebs-csi-driver-operator"
              - "system:serviceaccount:openshift-cluster-csi-drivers:aws-ebs-csi-driver-controller-sa"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  IAMRole00(Cluster_Name)openshiftimageregistryinstallercloudcredentials:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-image-registry-installer-cloud-cred"
      Description: "OpenShift role for openshift-image-registry/installer-cloud-credentials"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "s3:CreateBucket"
            - "s3:DeleteBucket"
            - "s3:PutBucketTagging"
            - "s3:GetBucketTagging"
            - "s3:PutBucketPublicAccessBlock"
            - "s3:GetBucketPublicAccessBlock"
            - "s3:PutEncryptionConfiguration"
            - "s3:GetEncryptionConfiguration"
            - "s3:PutLifecycleConfiguration"
            - "s3:GetLifecycleConfiguration"
            - "s3:GetBucketLocation"
            - "s3:ListBucket"
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
            - "s3:ListBucketMultipartUploads"
            - "s3:AbortMultipartUpload"
            - "s3:ListMultipartUploadParts"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-image-registry-installer-cloud-cred"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub:
              - "system:serviceaccount:openshift-image-registry:cluster-image-registry-operator"
              - "system:serviceaccount:openshift-image-registry:registry"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  S3Bucket00(Cluster_Name)oidc:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        BlockPublicAcls: true
      BucketName: "(Cluster_Name)-oidc"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: false
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
      - Value: "(Cluster_Name)"
        Key: "Name"
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
  IAMRole00(Cluster_Name)openshiftmachineapiawscloudcredentials:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-machine-api-aws-cloud-credentials"
      Description: "OpenShift role for openshift-machine-api/aws-cloud-credentials"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "ec2:CreateTags"
            - "ec2:DescribeAvailabilityZones"
            - "ec2:DescribeDhcpOptions"
            - "ec2:DescribeImages"
            - "ec2:DescribeInstances"
            - "ec2:DescribeInstanceTypes"
            - "ec2:DescribeInternetGateways"
            - "ec2:DescribeSecurityGroups"
            - "ec2:DescribeRegions"
            - "ec2:DescribeSubnets"
            - "ec2:DescribeVpcs"
            - "ec2:RunInstances"
            - "ec2:TerminateInstances"
            - "elasticloadbalancing:DescribeLoadBalancers"
            - "elasticloadbalancing:DescribeTargetGroups"
            - "elasticloadbalancing:DescribeTargetHealth"
            - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
            - "elasticloadbalancing:RegisterTargets"
            - "elasticloadbalancing:DeregisterTargets"
            - "iam:PassRole"
            - "iam:CreateServiceLinkedRole"
            Effect: "Allow"
          - Resource: "*"
            Action:
            - "kms:Decrypt"
            - "kms:Encrypt"
            - "kms:GenerateDataKey"
            - "kms:GenerateDataKeyWithoutPlainText"
            - "kms:DescribeKey"
            Effect: "Allow"
          - Condition:
              Bool:
                kms:GrantIsForAWSResource: true
            Resource: "*"
            Action:
            - "kms:RevokeGrant"
            - "kms:CreateGrant"
            - "kms:ListGrants"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-machine-api-aws-cloud-credentials"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub: "system:serviceaccount:openshift-machine-api:machine-api-controllers"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  IAMRole00(Cluster_Name)openshiftingressoperatorcloudcredentials:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-ingress-operator-cloud-credentials"
      Description: "OpenShift role for openshift-ingress-operator/cloud-credentials"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "elasticloadbalancing:DescribeLoadBalancers"
            - "route53:ListHostedZones"
            - "route53:ListTagsForResources"
            - "route53:ChangeResourceRecordSets"
            - "tag:GetResources"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-ingress-operator-cloud-credentials"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub: "system:serviceaccount:openshift-ingress-operator:ingress-operator"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  S3BucketPolicy00(Cluster_Name)oidc:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Retain"
    Properties:
      Bucket:
        Ref: "S3Bucket00(Cluster_Name)oidc00hjpeY"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "arn:aws:s3:::(Cluster_Name)-oidc/*"
          Action: "s3:GetObject"
          Effect: "Allow"
          Principal: "*"
          Sid: "AllowReadPublicAccess"
  IAMOIDCProvider00oidcprovider(Cluster_Name)oidcs3useast2amazonaws:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::OIDCProvider"
    DeletionPolicy: "Retain"
    Properties:
      ClientIdList:
      - "openshift"
      - "sts.amazonaws.com"
      ThumbprintList:
      - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
      Url: "https://(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  IAMRole00(Cluster_Name)openshiftcloudnetworkconfigcontroller:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-cloud-network-config-controller-clo"
      Description: "OpenShift role for openshift-cloud-network-config-controller/cloud-credentials"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "ec2:DescribeInstances"
            - "ec2:DescribeInstanceStatus"
            - "ec2:DescribeInstanceTypes"
            - "ec2:UnassignPrivateIpAddresses"
            - "ec2:AssignPrivateIpAddresses"
            - "ec2:UnassignIpv6Addresses"
            - "ec2:AssignIpv6Addresses"
            - "ec2:DescribeSubnets"
            - "ec2:DescribeNetworkInterfaces"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-cloud-network-config-controller-clo"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub: "system:serviceaccount:openshift-cloud-network-config-controller:cloud-network-config-controller"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
  IAMRole00(Cluster_Name)openshiftcloudcredentialoperatorcloudcre:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      MaxSessionDuration: 3600
      RoleName: "(Cluster_Name)-openshift-cloud-credential-operator-cloud-cre"
      Description: "OpenShift role for openshift-cloud-credential-operator/cloud-credential-operator-iam-ro-creds"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: "*"
            Action:
            - "iam:GetUser"
            - "iam:GetUserPolicy"
            - "iam:ListAccessKeys"
            Effect: "Allow"
        PolicyName: "(Cluster_Name)-openshift-cloud-credential-operator-cloud-cre"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              (Cluster_Name)-oidc.s3.us-east-2.amazonaws.com:sub: "system:serviceaccount:openshift-cloud-credential-operator:cloud-credential-operator"
          Action: "sts:AssumeRoleWithWebIdentity"
          Effect: "Allow"
          Principal:
            Federated: "arn:aws:iam::(Account_ID):oidc-provider/(Cluster_Name)-oidc.s3.us-east-2.amazonaws.com"
      Tags:
      - Value: "owned"
        Key: "openshift.io/cloud-credential-operator/(Cluster_Name)"
      - Value: "(Cluster_Name)"
        Key: "Name"
